=== NilFoundation/zkEVM-framework/libs/block_generator/resources/block_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type" :"object",
    "description": "Block data",
    "$defs": {
        "transaction_type" : {
            "enum" : ["ContractCreation", "NullTransaction", "MessageCall"]
        },

        "address": {
            "type":"string",
            "pattern": "^0x[0-9a-f]+$",
            "minLength": 42,
            "maxLength": 42
        },

        "transaction" : {
            "type": "object",
            "description": "Transaction data",
            "properties": {
                "id" :{
                    "type": "integer",
                    "minimum": 0
                },
                "type": {
                    "$ref": "#/$defs/transaction_type"
                },
                "nonce": {
                    "type": "integer",
                    "minimum": 0
                },
                "value": {
                    "type": "integer",
                    "minimum": 0
                },
                "receive_address": {
                    "$ref": "#/$defs/address"
                },
                "gas_price": {
                    "type": "integer",
                    "minimum": 0
                },
                "gas": {
                    "type": "integer",
                    "minimum": 0
                },
                "data": {
                    "type":"string",
                    "pattern": "^0x[0-9a-f]+$"
                },
                "sender": {
                    "$ref": "#/$defs/address"
                }
            },
            "required": ["id", "type", "nonce", "value", "receive_address", "gas_price", "gas", "data", "sender"],
            "additionalProperties": false
        },

        "account_block": {
            "type":"object",
            "description": "Account block data",
            "properties": {
                "account_address" :{
                    "$ref": "#/$defs/address"
                },
                "transactions": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "minimum": 0,
                        "uniqueItems": true
                    }
                }
            },
            "required": ["account_address", "transactions"],
            "additionalProperties": false
        },

        "block_header": {
            "type": "object",
            "description": "Block header data",
            "properties": {
                "parent_hash": {
                    "type": "integer",
                    "minimum": 0
                },
                "number": {
                    "type": "integer",
                    "minimum": 0
                },
                "gas_limit": {
                    "type": "integer",
                    "minimum": 0
                },
                "gas_used": {
                    "type": "integer",
                    "minimum": 0
                },
                "coinbase": {
                    "$ref": "#/$defs/address"
                },
                "prevrandao": {
                    "type": "integer",
                    "minimum": 0
                },
                "chain_id": {
                    "type": "integer",
                    "minimum": 0
                },
                "basefee": {
                    "type": "integer",
                    "minimum": 0
                },
                "blob_basefee": {
                    "type": "integer",
                    "minimum": 0
                },
                "timestamp": {
                    "type": "integer",
                    "minimum": 0
                }
            },
            "required": ["parent_hash", "number", "gas_limit", "gas_used", "coinbase",
                         "prevrandao", "chain_id", "basefee", "blob_basefee", "timestamp"],
            "additionalProperties": false
        },

        "message": {
            "type": "object",
            "description": "Common message data",
            "properties": {
                "src": {
                    "$ref": "#/$defs/address"
                },
                "dst": {
                    "$ref": "#/$defs/address"
                },
                "value": {
                    "type": "integer",
                    "minimum": 0
                },
                "transaction": {
                    "type": "integer",
                    "minimum": 0,
                    "description": "Id of a transaction"
                }
            },
            "required": ["src", "dst", "value", "transaction"],
            "additionalProperties": false
        }
    },


    "properties": {
        "previous_header": {
            "description": "Block header for previous block",
            "$ref": "#/$defs/block_header"
        },
        "current_header": {
            "description": "Block header of current block",
            "$ref": "#/$defs/block_header"
        },
        "account_blocks": {
            "type":"array",
            "description": "List of account blocks",
            "items": {
                "$ref": "#/$defs/account_block",
                "uniqueItems": true
            }
        },
        "transactions": {
            "type": "array",
            "description": "List of transactions",
            "items": {
                "$ref": "#/$defs/transaction",
                "uniqueItems": true
            }
        },
        "input_messages": {
            "type": "array",
            "description": "List of input messages",
            "items": {
                "$ref": "#/$defs/message",
                "uniqueItems": true
            }
        },
        "output_messages": {
            "type": "array",
            "description": "List of output messages",
            "items": {
                "$ref": "#/$defs/message",
                "uniqueItems": true
            }
        }
    },
    "required": ["previous_header", "current_header", "account_blocks", "transactions", "input_messages", "output_messages"],
    "additionalProperties": false
}

=== NilFoundation/zkEVM-framework/bin/assigner/example_data/call_block.json
{
    "previous_header" : {
        "parent_hash" : 0,
        "number" : 1,
        "gas_limit" : 2,
        "gas_used" : 3,
        "coinbase" : "0x0000000000000000000000000000000000000005",
        "prevrandao" : 4,
        "chain_id" : 1,
        "basefee" : 55,
        "blob_basefee" : 55,
        "timestamp" : 5
    },
    "current_header" : {
        "parent_hash" : 0,
        "number" : 1,
        "gas_limit" : 2,
        "gas_used" : 3,
        "coinbase" : "0x0000000000000000000000000000000000000005",
        "prevrandao" : 4,
        "chain_id" : 1,
        "basefee" : 55,
        "blob_basefee" : 55,
        "timestamp" : 5
    },
    "transactions" : [
        {
            "id" : 0,
            "type" : "MessageCall",
            "nonce" : 1,
            "value" : 2,
            "receive_address" : "0x0000000000000000000000000000000000000003",
            "gas_price" : 3,
            "gas" : 200000,
            "data" : "0xd09de08a",
            "sender" : "0x0000000000000000000000000000000000000002"
        }
    ],
    "account_blocks" : [
        {
            "account_address" : "0x0000000000000000000000000000000000000003",
            "transactions" : [0]
        }
    ],
    "input_messages" : [
        {
            "src" : "0x0000000000000000000000000000000000000002",
            "dst" : "0x0000000000000000000000000000000000000003",
            "value" : 0,
            "transaction" : 0
        }
    ],
    "output_messages" : []
}

=== NilFoundation/zkEVM-framework/tests/libs/block_generator/inputs/block.json
{
    "transactions" : [
        {
            "id" : 1,
            "type" : "ContractCreation",
            "nonce" : 95,
            "value" : 4,
            "receive_address" : "0x9bfa97dd7c7bb1c4b4c8bc5cf0ec41eeaf4d388d",
            "gas_price" : 8,
            "gas" : 45000,
            "data" : "0xb886b9dec50e17307d0a5579d8a315b33e98ece484eac2c6",
            "sender" : "0xca4bd01daa338beccd57f5e4a07557797f7b5e64"
        },
        {
            "id" : 2,
            "type" : "NullTransaction",
            "nonce" : 112,
            "value" : 1,
            "receive_address" : "0xf4ae4a37b33461aa3bf03d169c437a4ca310e968",
            "gas_price" : 14,
            "gas" : 42000,
            "data" : "0xdcfa22cc12f5e3dd7c4af3ca85abb05ec645ddbe8a3193cdb2",
            "sender" : "0x461fb6cb83437a5a2ae3e836fd91a4f9a5f39d4f"
        },
        {
            "id" : 8,
            "type" : "MessageCall",
            "nonce" : 1122,
            "value" : 6,
            "receive_address" : "0x9dd0fe11122b8c1421f334e88ef83b428f422564",
            "gas_price" : 3,
            "gas" : 2000,
            "data" : "0x6fe7ce79dc",
            "sender" : "0x59bfb5a33a46ca115aac1b2d647f9a54ffae21c0"
        }
    ],
    "previous_header" : {
        "parent_hash" : 28,
        "number" : 42,
        "gas_limit" : 500000,
        "gas_used" : 123000,
        "coinbase" : "0x26cc4b51f5b4b5b8bff4342dfc95d560bdbf9705",
        "prevrandao" : 66,
        "chain_id" : 3,
        "basefee" : 3,
        "blob_basefee" : 8,
        "timestamp" : 547675436587
    },
    "current_header" : {
        "parent_hash" : 128,
        "number" : 48,
        "gas_limit" : 500000,
        "gas_used" : 133000,
        "coinbase" : "0x8e7e6a2463079a0ebd8cddabba98a086ceaa5c27",
        "prevrandao" : 36,
        "chain_id" : 3,
        "basefee" : 3,
        "blob_basefee" : 14,
        "timestamp" : 547675436597
    },
    "account_blocks" : [
        {
            "account_address" : "0x5b0dd93b8d866d5d54e4e4b55eb5c620cb9eaf53",
            "transactions" : [1, 2]
        },
        {
            "account_address" : "0xee489f6ccdbe4583c11fa7d76c46694943d8690a",
            "transactions" : [1, 8]
        }
    ],
    "input_messages" : [
        {
            "src" : "0xca4bd01daa338beccd57f5e4a07557797f7b5e64",
            "dst" : "0x9bfa97dd7c7bb1c4b4c8bc5cf0ec41eeaf4d388d",
            "value" : 4,
            "transaction" : 1
        }
    ],
    "output_messages" : [
        {
            "src" : "0x461fb6cb83437a5a2ae3e836fd91a4f9a5f39d4f",
            "dst" : "0xf4ae4a37b33461aa3bf03d169c437a4ca310e968",
            "value" : 1,
            "transaction" : 2
        }
    ]
}

=== NilFoundation/zkEVM-framework/tests/libs/block_generator/inputs/scheme.json
{
	"previous_header" : {
	  "parent_hash" : 0,
	  "number" : 0,
	  "gas_limit" : 0,
	  "gas_used" : 0,
	  "coinbase" : "0x3aa33aa33aa33aa33aa33aa33aa33aa33aa33aa3",
	  "prevrandao" : 0,
	  "chain_id" : 0,
	  "basefee" : 0,
	  "blob_basefee" : 0,
	  "timestamp" : 0
	},
	"current_header" : {
      "parent_hash" : 0,
	  "number" : 0,
	  "gas_limit" : 0,
	  "gas_used" : 0,
	  "coinbase" : "0x3aa33aa33aa33aa33aa33aa33aa33aa33aa33aa3",
	  "prevrandao" : 0,
	  "chain_id" : 0,
	  "basefee" : 0,
	  "blob_basefee" : 0,
	  "timestamp" : 0
	},
	"transactions" : [
		{
			"id" : 0,
			"type" : "ContractCreation",
			"nonce" : 0,
			"value" : 0,
			"receive_address" : "0x3aa33aa33aa33aa33aa33aa33aa33aa33aa33aa3",
			"gas_price" : 0,
			"gas" : 0,
			"data" : "0x3a3a4a",
			"sender" : "0x3aa33aa33aa33aa33aa33aa33aa33aa33aa33aa3"
		}
	],
  "account_blocks" : [
	  {
		  "account_address" : "0x3aa33aa33aa33aa33aa33aa33aa33aa33aa33aa3",
		  "transactions" : [0]
	  },
	  {
		  "account_address" : "0x3aa33aa33aa33aa33aa33aa33aa33aa33aa33aa3",
          "transactions" : [0]
	  }
  ],
  "input_messages" : [
	  {
		  "src" : "0x3aa33aa33aa33aa33aa33aa33aa33aa33aa33aa3",
		  "dst" : "0x3aa33aa33aa33aa33aa33aa33aa33aa33aa33aa3",
		  "value" : 0,
		  "transaction" : 0
	  }
  ],
  "output_messages" : [
	  {
		  "src" : "0x3aa33aa33aa33aa33aa33aa33aa33aa33aa33aa3",
		  "dst" : "0x3aa33aa33aa33aa33aa33aa33aa33aa33aa33aa3",
		  "value" : 0,
		  "transaction" : 0
	  }
  ]
}
